# baseURL = "https://school.deuo.one/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Deuo Network - School Links"
copyright = "ZenDeuo ©2023"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "ZenDeuo"
headline = "Your One-Stop Shop For Quick Redirects At School ^-^"
image = "author.jpg"  # path relative to static directory

  links = [
  	{ link = { href = "https://docs.google.com/a/kingarthurs.org.uk", text = "Google Docs", icon = "link" } },
	{ link = { href = "https://classroom.google.com/a/kingarthurs.org.uk", text = "Google Classroom", icon = "link" } },
	{ link = { href = "https://office.com/login", text = "Microsoft Office 365", icon = "link" } },
	{ link = { href = "https://intranet.kingarthurs.org.uk", text = "Intranet", icon = "link" } },
	{ link = { href = "https://intranet.kingarthurs.org.uk/StudentProfile", text = "Student Profile", icon = "link" } },
	{ link = { href = "https://intranet.kingarthurs.org.uk/StudentProfile/timetable.html", text = "Timetable - Student Profile", icon = "link" } },
	{ link = { href = "https://files.sast.org.uk/home", text = "Foldr", icon = "link" } },
	{ link = { href = "https://members.gcsepod.com/podauth/sso/kingarthurs", text = "GCSE Pod", icon = "link" } },
	{ link = { href = "https://www.doddlelearn.co.uk/app/login", text = "Doddle Learn", icon = "link" } },
	{ link = { href = "https://app.senecalearning.com/login", text = "Seneca Learning", icon = "link" } },
	{ link = { href = "https://kingarthurs.org.uk", text = "KA Landing Page", icon = "link" } },
	{ link = { href = "http://status.sast.org.uk", text = "KA & Other Server Stats", icon = "link" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"